"""Add status to conexions

Revision ID: 29677494b3af
Revises: a9ec99b02bf5
Create Date: 2025-11-24 21:25:01.266542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29677494b3af'
down_revision: Union[str, None] = 'a9ec99b02bf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Verificar si la columna ya existe antes de agregarla
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('connections')]
    
    # Si ya existe 'active' (renombrada desde status) o 'status', no hacer nada
    if 'status' not in columns and 'active' not in columns:
        op.add_column('connections', sa.Column('status', sa.String(length=20), server_default='SIN INICIAR', nullable=False))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connections', 'status')
    # ### end Alembic commands ###
