"""add update_files

Revision ID: 316d77df3260
Revises: create_data_upload
Create Date: 2025-11-25 22:14:46.245237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '316d77df3260'
down_revision: Union[str, None] = 'create_data_upload'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_data_upload_identifier', table_name='data_upload')
    op.create_index(op.f('ix_data_upload_identifier'), 'data_upload', ['identifier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_upload_identifier'), table_name='data_upload')
    op.create_index('ix_data_upload_identifier', 'data_upload', ['identifier'], unique=True)
    # ### end Alembic commands ###

