"""add assignments table

Revision ID: 59292210906c
Revises: ad972367a21f
Create Date: 2025-11-28 22:51:22.551304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59292210906c'
down_revision: Union[str, None] = 'ad972367a21f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignments',
    sa.Column('id_assignment', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('intervention_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id_employee'], ),
    sa.ForeignKeyConstraint(['intervention_id'], ['interventions.id_interventions'], ),
    sa.PrimaryKeyConstraint('id_assignment')
    )
    op.create_index(op.f('ix_assignments_id_assignment'), 'assignments', ['id_assignment'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assignments_id_assignment'), table_name='assignments')
    op.drop_table('assignments')
    # ### end Alembic commands ###

