"""add sector_id to tanks pipes connections

Revision ID: 676567411805
Revises: c7ad0c5c2dcf
Create Date: 2025-11-27 14:01:38.663354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '676567411805'
down_revision: Union[str, None] = 'c7ad0c5c2dcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Verificar si la tabla sectors ya existe antes de crearla
    # (puede existir si se creó automáticamente al ejecutar el programa)
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()
    
    if 'sectors' not in tables:
        op.create_table('sectors',
        sa.Column('id_sector', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('active', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id_sector')
        )
        op.create_index(op.f('ix_sectors_id_sector'), 'sectors', ['id_sector'], unique=False)
        op.create_index(op.f('ix_sectors_name'), 'sectors', ['name'], unique=True)
    else:
        # Si la tabla ya existe, asegurarse de que los índices existan
        indexes = [idx['name'] for idx in inspector.get_indexes('sectors')]
        if 'ix_sectors_id_sector' not in indexes:
            op.create_index(op.f('ix_sectors_id_sector'), 'sectors', ['id_sector'], unique=False)
        if 'ix_sectors_name' not in indexes:
            op.create_index(op.f('ix_sectors_name'), 'sectors', ['name'], unique=True)
    
    # Eliminar índices y tabla files solo si existen
    if 'files' in tables:
        # Obtener todos los índices de la tabla files
        files_indexes = [idx['name'] for idx in inspector.get_indexes('files')]
        
        # Eliminar índices solo si existen
        index_names = ['ix_files_canon', 'ix_files_cat_service', 'ix_files_cologne', 
                      'ix_files_id', 'ix_files_taxpayer', 'ix_files_total']
        for index_name in index_names:
            if index_name in files_indexes:
                op.drop_index(index_name, table_name='files')
        
        # Eliminar la tabla files
        op.drop_table('files')
    
    # Agregar columnas sector_id solo si no existen
    if 'connections' in tables:
        connection_columns = [col['name'] for col in inspector.get_columns('connections')]
        if 'sector_id' not in connection_columns:
            op.add_column('connections', sa.Column('sector_id', sa.Integer(), nullable=True))
            op.create_foreign_key(None, 'connections', 'sectors', ['sector_id'], ['id_sector'])
        else:
            # Verificar si la foreign key ya existe
            fks = inspector.get_foreign_keys('connections')
            fk_exists = any(fk['referred_table'] == 'sectors' and 'sector_id' in fk['constrained_columns'] for fk in fks)
            if not fk_exists:
                op.create_foreign_key(None, 'connections', 'sectors', ['sector_id'], ['id_sector'])
    
    # Agregar foreign keys para intervention_entities y pipe_connections solo si no existen
    if 'intervention_entities' in tables:
        fks = inspector.get_foreign_keys('intervention_entities')
        fk_exists = any(fk['referred_table'] == 'pipes' and 'id_pipes' in fk['constrained_columns'] for fk in fks)
        if not fk_exists:
            op.create_foreign_key(None, 'intervention_entities', 'pipes', ['id_pipes'], ['id_pipes'], ondelete='CASCADE')
    
    if 'pipe_connections' in tables:
        fks = inspector.get_foreign_keys('pipe_connections')
        fk_exists = any(fk['referred_table'] == 'pipes' and 'pipe_id' in fk['constrained_columns'] for fk in fks)
        if not fk_exists:
            op.create_foreign_key(None, 'pipe_connections', 'pipes', ['pipe_id'], ['id_pipes'], ondelete='CASCADE')
    
    if 'pipes' in tables:
        pipes_columns = [col['name'] for col in inspector.get_columns('pipes')]
        if 'sector_id' not in pipes_columns:
            op.add_column('pipes', sa.Column('sector_id', sa.Integer(), nullable=True))
            op.create_foreign_key(None, 'pipes', 'sectors', ['sector_id'], ['id_sector'])
        else:
            # Verificar si la foreign key ya existe
            fks = inspector.get_foreign_keys('pipes')
            fk_exists = any(fk['referred_table'] == 'sectors' and 'sector_id' in fk['constrained_columns'] for fk in fks)
            if not fk_exists:
                op.create_foreign_key(None, 'pipes', 'sectors', ['sector_id'], ['id_sector'])
    
    if 'tank_pipes' in tables:
        fks = inspector.get_foreign_keys('tank_pipes')
        fk_exists = any(fk['referred_table'] == 'pipes' and 'pipe_id' in fk['constrained_columns'] for fk in fks)
        if not fk_exists:
            op.create_foreign_key(None, 'tank_pipes', 'pipes', ['pipe_id'], ['id_pipes'], ondelete='CASCADE')
    
    if 'tanks' in tables:
        tanks_columns = [col['name'] for col in inspector.get_columns('tanks')]
        if 'sector_id' not in tanks_columns:
            op.add_column('tanks', sa.Column('sector_id', sa.Integer(), nullable=True))
            op.create_foreign_key(None, 'tanks', 'sectors', ['sector_id'], ['id_sector'])
        else:
            # Verificar si la foreign key ya existe
            fks = inspector.get_foreign_keys('tanks')
            fk_exists = any(fk['referred_table'] == 'sectors' and 'sector_id' in fk['constrained_columns'] for fk in fks)
            if not fk_exists:
                op.create_foreign_key(None, 'tanks', 'sectors', ['sector_id'], ['id_sector'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tanks', type_='foreignkey')
    op.drop_column('tanks', 'sector_id')
    op.drop_constraint(None, 'tank_pipes', type_='foreignkey')
    op.drop_constraint(None, 'pipes', type_='foreignkey')
    op.drop_column('pipes', 'sector_id')
    op.drop_constraint(None, 'pipe_connections', type_='foreignkey')
    op.drop_constraint(None, 'intervention_entities', type_='foreignkey')
    op.drop_constraint(None, 'connections', type_='foreignkey')
    op.drop_column('connections', 'sector_id')
    op.create_table('files',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('taxpayer', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('cologne', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('cat_service', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('canon', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('excess', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('total', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='files_pkey')
    )
    op.create_index('ix_files_total', 'files', ['total'], unique=False)
    op.create_index('ix_files_taxpayer', 'files', ['taxpayer'], unique=False)
    op.create_index('ix_files_id', 'files', ['id'], unique=False)
    op.create_index('ix_files_cologne', 'files', ['cologne'], unique=False)
    op.create_index('ix_files_cat_service', 'files', ['cat_service'], unique=False)
    op.create_index('ix_files_canon', 'files', ['canon'], unique=False)
    op.drop_index(op.f('ix_sectors_name'), table_name='sectors')
    op.drop_index(op.f('ix_sectors_id_sector'), table_name='sectors')
    op.drop_table('sectors')
    # ### end Alembic commands ###

