"""add sector_id to tanks pipes connections

Revision ID: 676567411805
Revises: c7ad0c5c2dcf
Create Date: 2025-11-27 14:01:38.663354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '676567411805'
down_revision: Union[str, None] = 'c7ad0c5c2dcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sectors',
    sa.Column('id_sector', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_sector')
    )
    op.create_index(op.f('ix_sectors_id_sector'), 'sectors', ['id_sector'], unique=False)
    op.create_index(op.f('ix_sectors_name'), 'sectors', ['name'], unique=True)
    op.drop_index('ix_files_canon', table_name='files')
    op.drop_index('ix_files_cat_service', table_name='files')
    op.drop_index('ix_files_cologne', table_name='files')
    op.drop_index('ix_files_id', table_name='files')
    op.drop_index('ix_files_taxpayer', table_name='files')
    op.drop_index('ix_files_total', table_name='files')
    op.drop_table('files')
    op.add_column('connections', sa.Column('sector_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'connections', 'sectors', ['sector_id'], ['id_sector'])
    op.create_foreign_key(None, 'intervention_entities', 'pipes', ['id_pipes'], ['id_pipes'], ondelete='CASCADE')
    op.create_foreign_key(None, 'pipe_connections', 'pipes', ['pipe_id'], ['id_pipes'], ondelete='CASCADE')
    op.add_column('pipes', sa.Column('sector_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pipes', 'sectors', ['sector_id'], ['id_sector'])
    op.create_foreign_key(None, 'tank_pipes', 'pipes', ['pipe_id'], ['id_pipes'], ondelete='CASCADE')
    op.add_column('tanks', sa.Column('sector_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tanks', 'sectors', ['sector_id'], ['id_sector'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tanks', type_='foreignkey')
    op.drop_column('tanks', 'sector_id')
    op.drop_constraint(None, 'tank_pipes', type_='foreignkey')
    op.drop_constraint(None, 'pipes', type_='foreignkey')
    op.drop_column('pipes', 'sector_id')
    op.drop_constraint(None, 'pipe_connections', type_='foreignkey')
    op.drop_constraint(None, 'intervention_entities', type_='foreignkey')
    op.drop_constraint(None, 'connections', type_='foreignkey')
    op.drop_column('connections', 'sector_id')
    op.create_table('files',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('taxpayer', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('cologne', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('cat_service', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('canon', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('excess', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('total', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='files_pkey')
    )
    op.create_index('ix_files_total', 'files', ['total'], unique=False)
    op.create_index('ix_files_taxpayer', 'files', ['taxpayer'], unique=False)
    op.create_index('ix_files_id', 'files', ['id'], unique=False)
    op.create_index('ix_files_cologne', 'files', ['cologne'], unique=False)
    op.create_index('ix_files_cat_service', 'files', ['cat_service'], unique=False)
    op.create_index('ix_files_canon', 'files', ['canon'], unique=False)
    op.drop_index(op.f('ix_sectors_name'), table_name='sectors')
    op.drop_index(op.f('ix_sectors_id_sector'), table_name='sectors')
    op.drop_table('sectors')
    # ### end Alembic commands ###

