"""add url as text to roles

Revision ID: 8f9e5b46ecc0
Revises: 676567411805
Create Date: 2025-11-27 17:48:30.176793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f9e5b46ecc0'
down_revision: Union[str, None] = '676567411805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Verificar si la columna url ya existe antes de agregarla
    # (puede existir si se creó automáticamente al ejecutar el programa)
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()
    
    if 'roles' in tables:
        columns = [col['name'] for col in inspector.get_columns('roles')]
        if 'url' not in columns:
            op.add_column('roles', sa.Column('url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Verificar si la columna url existe antes de eliminarla
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()
    
    if 'roles' in tables:
        columns = [col['name'] for col in inspector.get_columns('roles')]
        if 'url' in columns:
            op.drop_column('roles', 'url')
    # ### end Alembic commands ###

