"""Add status to interventions

Revision ID: bbed30f095c2
Revises: 29677494b3af
Create Date: 2025-11-24 21:45:21.304096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbed30f095c2'
down_revision: Union[str, None] = '29677494b3af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connections', 'status')
    op.add_column('interventions', sa.Column('status', sa.String(length=20), server_default='SIN INICIAR', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interventions', 'status')
    op.add_column('connections', sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'SIN INICIAR'::character varying"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###

