"""add municipality and department to data_upload

Revision ID: c7ad0c5c2dcf
Revises: 316d77df3260
Create Date: 2025-11-25 22:44:59.498863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7ad0c5c2dcf'
down_revision: Union[str, None] = '316d77df3260'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_upload', sa.Column('municipality', sa.String(length=200), nullable=True))
    op.add_column('data_upload', sa.Column('department', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_data_upload_department'), 'data_upload', ['department'], unique=False)
    op.create_index(op.f('ix_data_upload_municipality'), 'data_upload', ['municipality'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_upload_municipality'), table_name='data_upload')
    op.drop_index(op.f('ix_data_upload_department'), table_name='data_upload')
    op.drop_column('data_upload', 'department')
    op.drop_column('data_upload', 'municipality')
    # ### end Alembic commands ###

