from app.controllers.Rol.rol import router as rol_router
from app.controllers.Employee.Emloyee import router as employee_router
from app.controllers.User.user import router as user_router
from app.controllers.auth.auth_controller import router as auth_router
from app.controllers.Tank.tank import router as tank_router
from app.controllers.Report.report import router as report_router
from app.controllers.permissions.permissions import router as permsission_router
from app.controllers.pipes.pipes import router as pipes_router
from app.controllers.Connection.connections import router as connection_router
from app.controllers.files.files import router as files_router
from app.controllers.type_employee.type_employees import router as type_employee_router
